name: test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: output list
      run: |
        nohup az webapp create-remote-connection --name as-mladenija-euw-dev-be-webapp-001 --resource-group freeresgroup1 --port 32771 &
        sudo apt-get install expect
        echo "#!/usr/bin/expect" >> loginscript.exp
        echo "set timeout -1" >> loginscript.exp
        echo "spawn ssh -p port_number user@hostname" >> loginscript.exp
        echo "expect {" >> loginscript.exp
        echo "  "*assword:" {" >> loginscript.exp
        echo "    send "your_password\r"" >> loginscript.exp
        echo "    exp_continue" >> loginscript.exp
        echo "  }" >> loginscript.exp
        echo "  "Last login:" {" >> loginscript.exp
        echo "    interact" >> loginscript.exp
        echo "  }" >> loginscript.exp
        echo "}" >> loginscript.exp
        chmod +x loginscript.exp
        ./loginscript.exp
        touch /home/site/wwwroot/testfile.txt
#        sshpass -p ${{ secrets.SIFRA_ZA_SSH_NA_APPSERVICE }} ssh -tt -p 32770 root@127.0.0.1 -o "StrictHostKeyChecking=no"
#        az webapp list --query "[?state=='Running']"
#        echo "See the running web apps up. My work here is done."
