# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# Author: Mladen Djuric

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # for manual run
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code 
      uses: actions/checkout@v3
      with:
        submodules: 'true' #recursive?
      # ssh-key: $ {{ secrets.PRIVATE_KEY_FOR_DEPLOY_KEY_IN_SUBMODULE }} , or \
      # token: $ {{ secrets.PAT_TOKEN }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
